rules:
  unpinned-uses:
    ignore:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

  artipacked:
    ignore:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
